#!/usr/bin/env bash
# Phase 1 of /docs-generate: create the apps/<product>/docs/ stub tree from
# apps/<product>/docs/.plan.yaml.
#
# Usage: _scaffold.sh <product>
#
# For each page in .plan.yaml, write a stub at <page-path> containing only YAML
# frontmatter (title, topic, diataxis, product, audience, sources: [], status: stub)
# and a single `# <Title>` line. Initialise apps/<product>/docs/.work/manifest.yaml.
#
# Idempotent: running again on an already-scaffolded tree leaves drafted /
# linked / reviewed pages untouched.

set -euo pipefail

PRODUCT="${1:-}"
if [[ -z "$PRODUCT" ]]; then
    echo "usage: _scaffold.sh <product>" >&2
    exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

cd "$WORKSPACE_ROOT"

PLAN="apps/$PRODUCT/docs/.plan.yaml"
if [[ ! -f "$PLAN" ]]; then
    echo "no plan at $PLAN — bootstrap one from apps/$PRODUCT/CLAUDE.md before scaffolding" >&2
    exit 1
fi

command -v yq >/dev/null 2>&1 || { echo "yq required" >&2; exit 1; }

mkdir -p "apps/$PRODUCT/docs"/{tutorials,how-to,explanation,reference} "apps/$PRODUCT/docs/.work/research"

manifest="apps/$PRODUCT/docs/.work/manifest.yaml"
{
    echo "# Auto-generated by /docs-generate scaffold phase. Do not hand-edit."
    echo "# Per-page status: stub | drafted | confluence-augmented | examples-added | linked | reviewed | needs-fix"
    echo "pages:"
} >"$manifest"

# Derive a Title Case title from the page basename.
titleize() {
    local base="$1"
    base="${base##*/}"
    base="${base%.md}"
    base="${base//-/ }"
    # Capitalise first letter of each word.
    awk '{for (i=1; i<=NF; i++) $i = toupper(substr($i,1,1)) substr($i,2); print}' <<<"$base"
}

# Derive the Diátaxis level from a page path: apps/<product>/docs/<level>/...
diataxis_of() {
    local p="$1"
    case "$p" in
        */tutorials/*)   echo tutorials   ;;
        */how-to/*)      echo how-to      ;;
        */reference/*)   echo reference   ;;
        */explanation/*) echo explanation ;;
        *)               echo ""          ;;
    esac
}

created=0
preserved=0

# Iterate keys under .pages
mapfile -t pages < <(yq -r '.pages | keys | .[]' "$PLAN")

for page in "${pages[@]}"; do
    topic=$(yq -r ".pages[\"$page\"].topic" "$PLAN")
    diataxis=$(diataxis_of "$page")
    mkdir -p "$(dirname "$page")"

    if [[ -f "$page" ]]; then
        # Preserve drafted / linked / reviewed pages. Re-stub only if status is
        # absent or already stub.
        existing_status=$(yq -r 'select(.status) | .status // "stub"' "$page" 2>/dev/null || echo stub)
        if [[ -n "$existing_status" && "$existing_status" != "stub" ]]; then
            echo "  \"$page\": { topic: \"$topic\", status: \"$existing_status\" }" >>"$manifest"
            preserved=$((preserved+1))
            continue
        fi
    fi

    title=$(titleize "$page")
    {
        echo "---"
        echo "title: $title"
        echo "topic: $topic"
        echo "diataxis: $diataxis"
        echo "product: $PRODUCT"
        echo "audience: both"
        echo "sources: []"
        echo "status: stub"
        echo "---"
        echo
        echo "# $title"
        echo
        echo "<!-- Stub. Populate via /docs-generate $PRODUCT --phase synth --page $page -->"
    } >"$page"

    echo "  \"$page\": { topic: \"$topic\", status: \"stub\" }" >>"$manifest"
    created=$((created+1))
done

# Seed README if absent — the linker will rewrite it later.
if [[ ! -f "apps/$PRODUCT/docs/README.md" ]]; then
    {
        echo "# $PRODUCT documentation"
        echo
        echo "<!-- Placeholder. Will be rewritten by /docs-generate $PRODUCT --phase link -->"
        echo
        echo "Run \`/docs-generate $PRODUCT\` to populate the pages under this tree."
        echo "See \`.claude/skills/docs-generate/SKILL.md\` for the workflow."
    } >"apps/$PRODUCT/docs/README.md"
fi

echo "Scaffolded apps/$PRODUCT/docs/ — created=$created, preserved=$preserved, manifest=$manifest"
