#!/usr/bin/env bash
# Phase 1 of /generate-ccd-docs: create the docs/ccd/ stub tree from plan.yaml.
#
# For each page in plan.yaml, write a stub at <page-path> containing only YAML
# frontmatter (topic, audience, sources: [], status: stub) and a single
# `# <Title>` line. Initialise docs/ccd/.work/manifest.yaml.
#
# Idempotent: running again on an already-scaffolded tree leaves drafted /
# linked / reviewed pages untouched.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLAN="$SCRIPT_DIR/plan.yaml"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

cd "$WORKSPACE_ROOT"

command -v yq >/dev/null 2>&1 || { echo "yq required" >&2; exit 1; }

mkdir -p docs/ccd/{tutorials,how-to,explanation,reference} docs/ccd/.work/research

manifest="docs/ccd/.work/manifest.yaml"
{
    echo "# Auto-generated by /generate-ccd-docs scaffold phase. Do not hand-edit."
    echo "# Per-page status: stub | drafted | examples-added | linked | reviewed | needs-fix"
    echo "pages:"
} >"$manifest"

# Derive a Title Case title from the page basename.
titleize() {
    local base="$1"
    base="${base##*/}"
    base="${base%.md}"
    base="${base//-/ }"
    # Capitalise first letter of each word.
    awk '{for (i=1; i<=NF; i++) $i = toupper(substr($i,1,1)) substr($i,2); print}' <<<"$base"
}

created=0
preserved=0

# Iterate keys under .pages
mapfile -t pages < <(yq -r '.pages | keys | .[]' "$PLAN")

for page in "${pages[@]}"; do
    topic=$(yq -r ".pages[\"$page\"].topic" "$PLAN")
    mkdir -p "$(dirname "$page")"

    if [[ -f "$page" ]]; then
        # Preserve drafted / linked / reviewed pages. Re-stub only if status is
        # absent or already stub.
        existing_status=$(yq -r 'select(.status) | .status // "stub"' "$page" 2>/dev/null || echo stub)
        if [[ -n "$existing_status" && "$existing_status" != "stub" ]]; then
            echo "  \"$page\": { topic: \"$topic\", status: \"$existing_status\" }" >>"$manifest"
            preserved=$((preserved+1))
            continue
        fi
    fi

    title=$(titleize "$page")
    {
        echo "---"
        echo "topic: $topic"
        echo "audience: both"
        echo "sources: []"
        echo "status: stub"
        echo "---"
        echo
        echo "# $title"
        echo
        echo "<!-- Stub. Populate via /generate-ccd-docs --phase synth --page $page -->"
    } >"$page"

    echo "  \"$page\": { topic: \"$topic\", status: \"stub\" }" >>"$manifest"
    created=$((created+1))
done

# Seed README if absent — the linker will rewrite it later.
if [[ ! -f docs/ccd/README.md ]]; then
    {
        echo "# CCD documentation"
        echo
        echo "<!-- Placeholder. Will be rewritten by /generate-ccd-docs --phase link -->"
        echo
        echo "Run \`/generate-ccd-docs\` to populate the pages under this tree."
        echo "See \`.claude/skills/generate-ccd-docs/SKILL.md\` for the workflow."
    } >docs/ccd/README.md
fi

echo "Scaffolded docs/ccd/ — created=$created, preserved=$preserved, manifest=$manifest"
